### ISSUE TITLE
[ERNIE] Request for the weights of "masked LM" and "next sentence prediction" layers

### ISSUE THREAD

**Issue by huntzhan** [PaddlePaddle/ERNIE#111]
Hi, could you help provide the weights of "masked LM" and "next sentence prediction" layers? Namely as followed:

```
cls/predictions/transform/dense/bias
cls/predictions/transform/dense/kernel
cls/predictions/transform/LayerNorm/beta
cls/predictions/transform/LayerNorm/gamma
cls/predictions/output_bias
cls/seq_relationship/output_bias
cls/seq_relationship/output_weights
```

It seems like the current release (1.0.1) does not contain those weights.

**Comment by linjianz** [comment]
Have you solved the problem yet?

**Comment by huntzhan** [comment]
> Have you solved the problem yet?

Nope. Those weights have never been published.

**Comment by linjianz** [comment]
@huntzhan I found that the prediction weights for masked LM are provided in the official ERNIE model. The map list between ERNIE and huggingface are:

```yml
{
        'mask_lm_trans_fc.b_0': 'cls.predictions.transform.dense.bias',
        'mask_lm_trans_fc.w_0': 'cls.predictions.transform.dense.weight',
        'mask_lm_trans_layer_norm_scale': 'cls.predictions.transform.LayerNorm.weight',
        'mask_lm_trans_layer_norm_bias': 'cls.predictions.transform.LayerNorm.bias',
        'mask_lm_out_fc.b_0': 'cls.predictions.bias'
}
```

You can use [ERNIE-Pytorch](https://github.com/nghuyong/ERNIE-Pytorch) to convert these weights to pytorch-form.
